language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
install:
  - gem install fakes3
  - npm install
before_script:
  - fakes3 -r /mnt/fakes3_root -p 4567 &
