sudo: required
services:
  - docker
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_script:
  - docker run -p "9444:9444" 66pix/s3ninja:latest &
  - sleep 10
addons:
  hosts:
    - node-s3-test.localhost
    - s3-bucket.localhost
